import { ForgotPassword } from "@/components/forgot-password";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forgot Password - Medi Direct",
  description: "Reset your Medi Direct account password",
  metadataBase: new URL("https://www.medi-direct.org/"),
  keywords: [
    "Medi Direct",
    "Healthcare",
    "Telemedicine",
    "Medical Services",
    "Patient Care",
    "Health Technology",
    "Online Consultation",
    "Medical Appointments",
    "Healthcare Solutions",
    "Health Management",
    "Remote Healthcare",
    "Digital Health",
    "Health Innovation",
    "Patient Support",
    "Wellness Services",
    "Health Monitoring",
    "Medical Advice",
    "Healthcare Accessibility",
    "Health Information",
    "Patient Engagement",
    "Healthcare Providers",
    "Medical Professionals",
    "Health Services",
    "Telehealth",
    "Virtual Healthcare",
    "Health Consultation",
    "Medical Technology",
    "Healthcare Platform",
    "Patient Portal",
    "Health Services Online",
    "Healthcare App",
    "Medical Records",
    "Health Tracking",
    "Wellness Management",
    "Health Solutions",
    "Healthcare Innovation",
    "Patient Care Solutions",
    "Health and Wellness",
    "Healthcare Accessibility",
    "Medical Services Online",
    "Health Consultation Services",
    "Remote Medical Care",
    "Digital Healthcare Solutions",
    "Patient-Centric Healthcare",
    "Healthcare Technology",
    "Health and Wellness Solutions",
    "Online Health Services",
    "Healthcare Management",
    "Patient-Centered Care",
    "Health and Wellness Platform",
    "Healthcare Accessibility Solutions",
    "Telemedicine Services",
    "Virtual Health Services",
    "Healthcare Innovation Solutions",
    "Health and Wellness Management",
    "Healthcare Solutions Online",
    "Patient Engagement Solutions",
    "Healthcare Providers Online",
    "Medical Professionals Online",
    "Health Services Online Platform",
    "Telehealth Services",
    "Virtual Healthcare Solutions",
    "Health Consultation Platform",
    "Medical Technology Solutions",
    "Healthcare Platform Online",
    "Patient Portal Services",
    "Health Services Online Platform",
    "Healthcare App Solutions",
    "Medical Records Management",
    "Health Tracking Solutions",
    "Wellness Management Solutions",
    "Health Solutions Online",
    "Healthcare Innovation Platform",
    "Patient Care Online",
    "Health and Wellness Online",
    "Healthcare Accessibility Platform",
    "Medical Services Online Platform",
    "Health Consultation Services Online",
    "Remote Medical Care Solutions",
    "Digital Healthcare Platform",
    "Patient-Centric Healthcare Solutions",
    "Healthcare Technology Solutions",
    "Health and Wellness Solutions Online",
    "Online Health Services Platform",
    "Healthcare Management Solutions",
    "Patient-Centered Care Solutions",
    "Health and Wellness Platform Online",
    "Healthcare Accessibility Solutions Online",
    "Telemedicine Online",
    "Virtual Health Services Online",
    "Healthcare Innovation Solutions Online",
    "Health and Wellness Management Solutions",
    "Healthcare Solutions Online Platform",
    "Patient Engagement Solutions Online",
    "Healthcare Providers Online Platform",
    "Medical Professionals Online Platform",
    "Health Services Online Platform Solutions",
    "Telehealth Online",
    "Virtual Healthcare Solutions Online",
    "Health Consultation Platform Online",
    "Medical Technology Solutions Online",
    "Healthcare Platform Online Solutions",
    "Patient Portal Services Online",
    "Health Services Online Platform Solutions",
    "Healthcare App Solutions Online",
    "Medical Records Management Solutions",
    "Health Tracking Solutions Online",
    "Wellness Management Solutions Online",
    "Health Solutions Online Platform",
    "Healthcare Innovation Platform Online",
    "Patient Care Online Solutions",
    "Health and Wellness Online Solutions",
    "Healthcare Accessibility Platform Online",
    "Medical Services Online Platform Solutions",
    "Health Consultation Services Online Platform",
    "Remote Medical Care Solutions Online",
    "Digital Healthcare Platform Online",
    "Patient-Centric Healthcare Solutions Online",
  ],
  icons: {
    icon: "/logo.jpg",
  },
  openGraph: {
    title: "Forgot Password - Medi Direct",
    description: "Reset your Medi Direct account password",
    url: "https://www.medidirect.org/forgot-password",
    siteName: "Medi Direct",
    images: {
      url: "https://res.cloudinary.com/dkvxi5iws/image/upload/v1751829214/logo_putfge.jpg",
      width: 1200,
      height: 630,
    },
  },
};

const ForgotPasswordPage = () => {
  return <ForgotPassword />;
};

export default ForgotPasswordPage;
